'numEpochs' : [10,2]
'batchSize': 512
'validationPercentage': 0
'threshold': 0.5
'maxwords': 50
'optLearningRates': [0.001,0.0001]
'optBeta1': 0.8
'optBeta2': 0.99
'optEpsilon': 0.001
'weightEmbeddings': true
'trainEmbeddings': false
'lossReweight': true
'lossWeightAdjust': 1
'categories':  ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

